// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `Conector.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Conector;

public class _ConfirmarMelodiaPrxI extends com.zeroc.Ice._ObjectPrxI implements ConfirmarMelodiaPrx
{
    public static final long serialVersionUID = 0L;
}
