# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.7.1
#
# <auto-generated>
#
# Generated from file `Conector.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Conector
_M_Conector = Ice.openModule('Conector')
__name__ = 'Conector'

_M_Conector._t_Escuchar = IcePy.defineValue('::Conector::Escuchar', Ice.Value, -1, (), False, True, None, ())

if 'EscucharPrx' not in _M_Conector.__dict__:
    _M_Conector.EscucharPrx = Ice.createTempClass()
    class EscucharPrx(Ice.ObjectPrx):

        def escucharNota(self, melodia, context=None):
            return _M_Conector.Escuchar._op_escucharNota.invoke(self, ((melodia, ), context))

        def escucharNotaAsync(self, melodia, context=None):
            return _M_Conector.Escuchar._op_escucharNota.invokeAsync(self, ((melodia, ), context))

        def begin_escucharNota(self, melodia, _response=None, _ex=None, _sent=None, context=None):
            return _M_Conector.Escuchar._op_escucharNota.begin(self, ((melodia, ), _response, _ex, _sent, context))

        def end_escucharNota(self, _r):
            return _M_Conector.Escuchar._op_escucharNota.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Conector.EscucharPrx.ice_checkedCast(proxy, '::Conector::Escuchar', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Conector.EscucharPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Conector::Escuchar'
    _M_Conector._t_EscucharPrx = IcePy.defineProxy('::Conector::Escuchar', EscucharPrx)

    _M_Conector.EscucharPrx = EscucharPrx
    del EscucharPrx

    _M_Conector.Escuchar = Ice.createTempClass()
    class Escuchar(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Conector::Escuchar', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Conector::Escuchar'

        @staticmethod
        def ice_staticId():
            return '::Conector::Escuchar'

        def escucharNota(self, melodia, current=None):
            raise NotImplementedError("servant method 'escucharNota' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Conector._t_EscucharDisp)

        __repr__ = __str__

    _M_Conector._t_EscucharDisp = IcePy.defineClass('::Conector::Escuchar', Escuchar, (), None, ())
    Escuchar._ice_type = _M_Conector._t_EscucharDisp

    Escuchar._op_escucharNota = IcePy.Operation('escucharNota', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_int, False, 0),), (), ((), IcePy._t_bool, False, 0), ())

    _M_Conector.Escuchar = Escuchar
    del Escuchar

_M_Conector._t_ConfirmarMelodia = IcePy.defineValue('::Conector::ConfirmarMelodia', Ice.Value, -1, (), False, True, None, ())

if 'ConfirmarMelodiaPrx' not in _M_Conector.__dict__:
    _M_Conector.ConfirmarMelodiaPrx = Ice.createTempClass()
    class ConfirmarMelodiaPrx(Ice.ObjectPrx):

        def confirmarcion(self, secuencia, context=None):
            return _M_Conector.ConfirmarMelodia._op_confirmarcion.invoke(self, ((secuencia, ), context))

        def confirmarcionAsync(self, secuencia, context=None):
            return _M_Conector.ConfirmarMelodia._op_confirmarcion.invokeAsync(self, ((secuencia, ), context))

        def begin_confirmarcion(self, secuencia, _response=None, _ex=None, _sent=None, context=None):
            return _M_Conector.ConfirmarMelodia._op_confirmarcion.begin(self, ((secuencia, ), _response, _ex, _sent, context))

        def end_confirmarcion(self, _r):
            return _M_Conector.ConfirmarMelodia._op_confirmarcion.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Conector.ConfirmarMelodiaPrx.ice_checkedCast(proxy, '::Conector::ConfirmarMelodia', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Conector.ConfirmarMelodiaPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Conector::ConfirmarMelodia'
    _M_Conector._t_ConfirmarMelodiaPrx = IcePy.defineProxy('::Conector::ConfirmarMelodia', ConfirmarMelodiaPrx)

    _M_Conector.ConfirmarMelodiaPrx = ConfirmarMelodiaPrx
    del ConfirmarMelodiaPrx

    _M_Conector.ConfirmarMelodia = Ice.createTempClass()
    class ConfirmarMelodia(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Conector::ConfirmarMelodia', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Conector::ConfirmarMelodia'

        @staticmethod
        def ice_staticId():
            return '::Conector::ConfirmarMelodia'

        def confirmarcion(self, secuencia, current=None):
            raise NotImplementedError("servant method 'confirmarcion' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Conector._t_ConfirmarMelodiaDisp)

        __repr__ = __str__

    _M_Conector._t_ConfirmarMelodiaDisp = IcePy.defineClass('::Conector::ConfirmarMelodia', ConfirmarMelodia, (), None, ())
    ConfirmarMelodia._ice_type = _M_Conector._t_ConfirmarMelodiaDisp

    ConfirmarMelodia._op_confirmarcion = IcePy.Operation('confirmarcion', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_int, False, 0), ())

    _M_Conector.ConfirmarMelodia = ConfirmarMelodia
    del ConfirmarMelodia

# End of module Conector
